name: habit_tracker
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  awesome_notifications: ^0.6.21
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_background_service: ^2.1.3
  flutter_riverpod: ^1.0.3
  hive: ^2.2.3
  intl: ^0.17.0
  mobility_features: ^3.1.0
  percent_indicator: ^4.2.0
  flutter_local_notifications: ^9.7.0
  background_fetch: ^1.1.0
  sqflite: ^2.0.3
  path: ^1.8.1
  move_to_background: ^1.0.2

dev_dependencies:

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
